In [3]:
import cv2
from tensorflow.keras.models import load_model
import numpy as np
from pydub import AudioSegment
from pydub.playback import play

c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)


In [4]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'D:/pratiksha/Prepared_Data/Models/model.h5.h5')

In [2]:
%pip install --upgrade opencv-python



  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/38/d2/3e8c13ffc37ca5ebc6f382b242b44acb43eb489042e1728407ac3904e72f/opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
    --------------------------------------- 0.5/38.1 MB 16.8 MB/s eta 0:00:03
   - -------------------------------------- 1.0/38.1 MB 12.6 MB/s eta 0:00:03
   - -------------------------------------- 1.4/38.1 MB 11.2 MB/s eta 0:00:04
   -- ------------------------------------- 1.9/38.1 MB 11.1 MB/s eta 0:00:04
   -- ------------------------------------- 2.4/38.1 MB 10.9 MB/s eta 0:00:04
   -- ------------------------------------- 2.7/38.1 MB 10.8 MB/s eta 0:00:04
   --- ------------------------------------ 3.1/38.1 MB 10.0 MB/s eta 0:00:04
   --- ------------------------------------ 3.4/38.1 MB 9.3 MB/s eta 0:00:04
   --- ------------------------------------ 3.7/38.1 MB 9.0 MB/s eta 0:00:04
   ---- 

In [5]:
import cv2
cap = cv2.VideoCapture(1)
ret, frame = cap.read()
ret

False

In [6]:
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)

    # Get the height and width of the frame
    height, width, _ = frame.shape
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        


    
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()
    

1/1 [==============================] - 15s 15s/step
[[0.5195812  0.48041877]]
1/1 [==============================] - 0s 61ms/step
[[0.52378815 0.47621185]]
1/1 [==============================] - 0s 86ms/step
[[0.24136735 0.75863266]]
1/1 [==============================] - 0s 54ms/step
[[0.14494331 0.8550567 ]]
1/1 [==============================] - 0s 57ms/step
[[0.5982071 0.4017929]]
1/1 [==============================] - 0s 63ms/step
[[0.861518   0.13848199]]
1/1 [==============================] - 0s 63ms/step
[[0.3805499 0.6194501]]
1/1 [==============================] - 0s 69ms/step
[[0.1263683 0.8736317]]
1/1 [==============================] - 0s 64ms/step
[[0.19270429 0.8072957 ]]
1/1 [==============================] - 0s 77ms/step
[[0.82463175 0.17536825]]
1/1 [==============================] - 0s 78ms/step
[[0.07290994 0.9270901 ]]
1/1 [==============================] - 0s 64ms/step
[[0.28945392 0.7105461 ]]
1/1 [==============================] - 0s 60ms/step
[[0.4191645  0.580

In [5]:
import pygame
from pygame import mixer

mixer.init()
sound= mixer.Sound(r'D:/pratiksha/Prepared_Data/alarm.wav')
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    if not ret:  # Check if frame was read successfully
        break
    
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        
        # if eyes are closed
        if prediction[0][0]>0.30:
            cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>15):
                try:
                    sound.play()
                except:
                    pass
            
        # if eyes are open
        elif prediction[0][1]>0.30:
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-1
            if (Score<0):
                Score=0
            
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

pygame 2.5.1 (SDL 2.28.2, Python 3.11.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
1/1 [==============================] - 14s 14s/step
[[0.40431353 0.59568644]]
1/1 [==============================] - 0s 148ms/step
[[0.7891667  0.21083337]]
1/1 [==============================] - 0s 94ms/step
[[0.05741008 0.9425899 ]]
1/1 [==============================] - 0s 93ms/step
[[0.59506446 0.4049355 ]]
1/1 [==============================] - 0s 87ms/step
[[0.06640954 0.9335905 ]]
1/1 [==============================] - 0s 93ms/step
[[0.19487837 0.8051216 ]]
1/1 [==============================] - 0s 91ms/step
[[0.59132093 0.40867904]]
1/1 [==============================] - 0s 91ms/step
[[0.690047  0.3099529]]
1/1 [==============================] - 0s 106ms/step
[[0.5036016 0.4963984]]
1/1 [==============================] - 0s 66ms/step
[[0.6664476  0.33355233]]
1/1 [==============================] - 0s 99ms/step
[[0.2904041  0.70959586]]
1/1 [==========================

In [6]:
import pygame
from pygame import mixer
import time

mixer.init()
sound = mixer.Sound(r'D:/pratiksha/Prepared_Data/alarm.wav')
cap = cv2.VideoCapture(0)
Score = 0

# Initialize timer variable
closed_eyes_duration = 0

while True:
    ret, frame = cap.read()
    if not ret:  # Check if frame was read successfully
        break

    height, width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.2, minNeighbors=3)
    eyes = eye_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=1)

    cv2.rectangle(frame, (0, height - 50), (200, height), (0, 0, 0), thickness=cv2.FILLED)

    for (x, y, w, h) in faces:
        cv2.rectangle(frame, pt1=(x, y), pt2=(x + w, y + h), color=(255, 0, 0), thickness=3)

    for (ex, ey, ew, eh) in eyes:
        cv2.rectangle(frame, pt1=(ex, ey), pt2=(ex + ew, ey + eh), color=(255, 0, 0), thickness=3)

        # preprocessing steps
        eye = frame[ey:ey + eh, ex:ex + ew]
        eye = cv2.resize(eye, (80, 80))
        eye = eye / 255
        eye = eye.reshape(80, 80, 3)
        eye = np.expand_dims(eye, axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)

        # if eyes are closed
        if prediction[0][0] > 0.30:
            # Start the timer
            start_time = time.time()

            # Clear text for open eyes
            cv2.putText(frame, '', (10, height - 20), fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL, fontScale=1,
                        color=(255, 255, 255), thickness=1, lineType=cv2.LINE_AA)

            cv2.putText(frame, 'Score' + str(Score), (100, height - 20), fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,
                        fontScale=1, color=(255, 255, 255), thickness=1, lineType=cv2.LINE_AA)
            Score = Score + 1
            if (Score > 15):
                try:
                    sound.play()
                except:
                    pass

        # if eyes are open
        elif prediction[0][1] > 0.90:
            # Stop the timer
            end_time = time.time()
            elapsed_time = end_time - start_time

            # Update the closed_eyes_duration variable
            closed_eyes_duration += elapsed_time
            cv2.putText(frame, 'open', (10, height - 20), fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL, fontScale=1,
                        color=(255, 255, 255), thickness=1, lineType=cv2.LINE_AA)

            # Decrement the score for open eyes
            Score = Score - 1
            if (Score < 0):
                Score = 0

            cv2.putText(frame, 'Score' + str(Score), (100, height - 20), fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,
                        fontScale=1, color=(255, 255, 255), thickness=1, lineType=cv2.LINE_AA)

    cv2.imshow('frame', frame)
    if cv2.waitKey(33) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


1/1 [==============================] - 0s 72ms/step
[[0.7162189 0.2837811]]
1/1 [==============================] - 0s 77ms/step
[[0.72230864 0.2776914 ]]
1/1 [==============================] - 0s 74ms/step
[[0.6757338  0.32426623]]
1/1 [==============================] - 0s 74ms/step
[[0.62576455 0.37423548]]
1/1 [==============================] - 0s 67ms/step
[[0.6721707  0.32782927]]
1/1 [==============================] - 0s 78ms/step
[[0.72017413 0.27982584]]
1/1 [==============================] - 0s 76ms/step
[[0.6756826  0.32431737]]
1/1 [==============================] - 0s 81ms/step
[[0.7502595 0.2497405]]
1/1 [==============================] - 0s 77ms/step
[[0.77476853 0.22523148]]
1/1 [==============================] - 0s 84ms/step
[[0.591098   0.40890202]]
1/1 [==============================] - 0s 77ms/step
[[0.7762991  0.22370093]]
1/1 [==============================] - 0s 129ms/step
[[0.68657863 0.31342137]]
1/1 [==============================] - 0s 73ms/step
[[0.57983273 0.

In [7]:
import pygame
from pygame import mixer
import time
import cv2

mixer.init()
sound= mixer.Sound(r'D:/pratiksha/Prepared_Data/alarm.wav')
cap = cv2.VideoCapture(0)
Score = 0
# Initialize timer variable
closed_eyes_duration = 0
while True:
    ret, frame = cap.read()
    if not ret:  # Check if frame was read successfully
        break
    
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        
        # if eyes are closed
        if prediction[0][0]>0.30:
            
            # Start the timer
            start_time = time.time()

            cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>15):
                try:
                    sound.play()
                except:
                    pass
            
        # if eyes are open
        elif prediction[0][1]>0.90:

            # Stop the timer
            end_time = time.time()
            elapsed_time = end_time - start_time

            # Update the closed_eyes_duration variable
            closed_eyes_duration += elapsed_time
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-1
            if (Score<0):
                Score=0
            
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 19s 19s/step
[[0.7754799  0.22452013]]
1/1 [==============================] - 0s 130ms/step
[[0.76874256 0.23125748]]
1/1 [==============================] - 0s 82ms/step
[[0.71119833 0.28880164]]
1/1 [==============================] - 0s 66ms/step
[[0.78171515 0.21828485]]
1/1 [==============================] - 0s 66ms/step
[[0.7610701  0.23892994]]
1/1 [==============================] - 0s 106ms/step
[[0.8283132  0.17168686]]
1/1 [==============================] - 0s 103ms/step
[[0.83533275 0.16466719]]
1/1 [==============================] - 0s 76ms/step
[[0.79323024 0.20676975]]
1/1 [==============================] - 0s 83ms/step
[[0.8873635  0.11263651]]
1/1 [==============================] - 0s 69ms/step
[[0.8033094  0.19669066]]
1/1 [==============================] - 2s 2s/step
[[0.78453374 0.21546626]]
1/1 [==============================] - 0s 185ms/step
[[0.7745803  0.22541969]]
1/1 [==============================] - 0s 66ms/step
[[0.696447

: 

: 